# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildVersion: 1.0.$(Build.BuildId)

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/MoaiFramework.csproj'
    arguments: --configuration $(buildConfiguration)

- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/MoaiFramework.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: buildVersion

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'